### ISSUE TITLE
Items Information Issue

### ISSUE THREAD

**Issue by tmkloster** [cptechinc/stat-crm#1]
![image](https://user-images.githubusercontent.com/31896390/31737621-befb1f4e-b40d-11e7-96a3-c8c103aa8d99.png)

**Comment by Pauldro** [comment]
@tmkloster I think this has to do with item search for ecomm. Since we base the salesportal search off it, I tried to run the WUD, but ran into a CAT TREE error which means it's trying to look at items in categories. I'll have curtis look at this.

**Comment by tmkloster** [comment]
Ok Thanks! :)
